### ISSUE TITLE
Design Matrix Class

### ISSUE THREAD

**Issue by ljchang** [ljchang/nltools#114]
We should add new design matrix class to nltools

**Data Fields**
.data - we get this from data.values cause of subclassing pandas
.sampling_frequency

**Methods**
- ~~vif~~ 
- ~~plot~~ 
- convolve - look up temporal derivatives
    - ~~hrf should take list of functions then loop over to apply convolution and change column names accordingly~~
  - ~~inplace = true~~
  - ~~column_list~~
  - variable name
- add_filter - check out luke matlab toolbox, maybe nilearn, direct cosine transform
- import_onset
- concat
   - add intercept
   - deal with run wise codes
-zscore - steal from utils
-downsample - steal from utils
-upsample - copy from downsample add to utils too

**Comment by ejolly** [comment]
- Make new function to read csvs and yield design matrix class as a utility function instead of putting it in design matrix init
- function should take flag about whether to add an intercept
- then append method on design matrix should handle 4 cases:
- handle 2 scenario: both have intercepts, or both dont otherwise raise error
 1) if they both dont, either make a single intercept, or runwise dummies
 2) if they both do, decide whether to stack them or separate them 
  - make sure even run dummies are called intercept, i.e. intercept_1, intercept_2... then can search within column names for intercept

**Comment by ljchang** [comment]
added with #116
