### ISSUE TITLE
Design_Matrix Needs add_intercept and has_intercept methods

### ISSUE THREAD

**Issue by ljchang** [ljchang/nltools#219]
@ejolly: There is currently no way to easily add an intercept that updates the metadata (that I can see).

This seems import for the concatenation methods.

**Comment by ejolly** [comment]
Yup sorry working on a PR that should solve all this but haven’t committed anything yet.

**Comment by ejolly** [comment]
So Design_Matrix as a method called `add_poly(int)` that takes an integer and adds polynomial terms to the matrix. If int == 0, thats an intercept, int == 1, intercept + linear trend, etc. There's also a flag to switch whether all lower order terms should be auto added if a higher level polynomial is requested. 

There's also a method called `.details()` which uses `__repr__` to present info about the Design Matrix such has what's convolved, sampling rate, and what polynomial columns (of which intercept is one), it has. The reason for this method, is because we're sub-classing pandas, the default `__repr__` is data frame values itself, unlike `Brain_Data` where the `__repr__` is totally custom.
