### ISSUE TITLE
Add support for BIDS

### ISSUE THREAD

**Issue by chrisfilo** [ljchang/nltools#41]
BIDS (http://bids.neuroimaging.io) is a new standard for organizing and describing neuroimaging datasets designed with automated analysis in mind. It's growing in popularity (for example all new datasets coming out of OpenfMRI are using it). Adding support for BIDS in neurolearn would make it easier to use for many researchers.

**Comment by ljchang** [comment]
@ejolly what might this look like?  is there a way to easily grab data and metadata?  I feel like this isn't really necessary at the moment with the [pybids](https://github.com/INCF/pybids) package

**Comment by ejolly** [comment]
I don’t this is necessary because of the level of abstraction at which nltools operates. Agree utilizing something like pybids a user can easily navigate a standard dataset structure and pass specific niftis to nltools. Don’t think nltools needs to bother with that. Although we can add a doc or tutorial example on how a user might do that to make things easier for users operating with the BIDS format.

**Comment by ljchang** [comment]
Let's write a tutorial at some point. closing this for now.

**Comment by chrisfilo** [comment]
Maybe it makes more sense for https://github.com/cosanlab/cosanlab_preproc? Point to a BIDS directory and run preprocessing?
